### ISSUE TITLE
[Error] ValueError: Failed to load model from file: ./models/7b/Llama-2-7b.ggmlv3.q4_0.bin

### ISSUE THREAD

**Issue by anilaphale** [OwenPendrighElliott/LocalMarqoQA#1]
Hi,

While trying to run this project I am facing ValueError: Failed to load model from file: ./models/7b/Llama-2-7b.ggmlv3.q4_0.bin

`  File "/Users/user/Desktop/prj/codes/LocalMarqoQA/backend/ai_chat.py", line 36, in <module>
    LLM = Llama(
          ^^^^^^
  File "/Users/user/Desktop/prj/codes/LocalMarqoQA/backend/env/lib/python3.11/site-packages/llama_cpp/llama.py", line 369, in __init__
    internals.LlamaModel(
  File "/Users/user/Desktop/prj/codes/LocalMarqoQA/backend/env/lib/python3.11/site-packages/llama_cpp/_internals.py", line 56, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: ./models/7b/Llama-2-7b.ggmlv3.q4_0.bin`

**Comment by anilaphale** [comment]
Found the issue and resolved. Thanks.

**Comment by OwenElliottDev** [comment]
I have neglected this repo a bit so it's currently setup for Marqo V1 (though I didn't pin any dependencies, whoops).

I'll make some quick updates to get this running with the latest Marqo version.

**Comment by OwenElliottDev** [comment]
@anilaphale I pushed updates to make it work with Marqo V2 and pinned the dependencies now. Let me know if you have issues or questions (LLaMa CPP changes mean I also changed the recommended model so check the README for a new link to one that works).
